### PR TITLE
add forkbomb in nim

### PR DESCRIPTION
**Pull request by array-in-a-matrix**

### CODE REVIEW

**Review by 0x4c756e61 — CHANGES_REQUESTED** [review]
Hi, why do you assign the return value of fork ? It isn't used after, that's why var is also useless here
why not do:
```nim
discard fork()
```
on line 4 ?

**Comment by array-in-a-matrix** [comment]
> Hi, why do you assign the return value of fork ? It isn't used after, that's why var is also useless here why not do:
> 
> ```nim
> discard fork()
> ```
> 
> on line 4 ?

Thank you. I updated the PR.

**Comment by 0x4c756e61** [comment]
> Thank you. I updated the PR.

No problem. Have a nice rest of your day/night

**Review by 0x4c756e61 — APPROVED** [review]

**Comment by aaronryank** [comment]
Nice one

**Pull request merged**
