### PR TITLE
Update the code to make it more idiomatic and rename fork-bomb.cc to fork-bomb.cpp

### PR DESCRIPTION
**Pull request by zencatalyst**
The standard file extension for C++ source files is .cpp and I also made the code a bit more modern and standard C++ compliant.

### CODE REVIEW

**Comment by Mart-Bogdan** [comment]
It is actually common in Unix to be .cc

That's mostly Microsoft flavor for it being .cpp

But generally both work.

**Comment by Mart-Bogdan** [comment]
P.S. more great issue is that it is using C library `cstdlib`  should it use something like [`std::thread`](https://en.cppreference.com/w/cpp/thread/thread)  instead?

**Comment by zencatalyst** [comment]
>should it use something like [`std::thread`](https://en.cppreference.com/w/cpp/thread/thread)  instead?

I don't think it's the right thing to do. The `std::thread` class does not start a new independent process the way `std::system(argv[0])` does. `std::thread` only starts a new software thread that runs as a child of the parent (main) thread. It is not suitable for the purpose of a fork bomb.

**Comment by Mart-Bogdan** [comment]
Yeah. That's true. But I see that many other langs implementations are jsut creating threads. Strange.

**Comment by aaronryank** [comment]
This is pointless, add some functionality or leave it alone

Langs that spawn threads - either that's the best they can do or it's the best I know how to do in said lang, feel free to fork and pr

**Comment by zencatalyst** [comment]
> This is pointless, add some functionality or leave it alone

There was no added functionality but I enhanced it by making it comply with CPP core guidelines. I don't know why you closed it.

**Pull request closed without merging**
